# -*- coding: utf-8 -*-
"""Cuaderno 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1teakLuoBIJ049FxdG1ZkiUYI4sWhMww2
"""



import pandas as pd
import numpy as np

df_estudiantes=pd.read_csv('/content/drive/MyDrive/p_hyton/StudentsPerformance (1).csv')
df_estudiantes

from google.colab import drive
drive.mount('/content/drive')

df_estudiantes

#operaciones entre columnas, lo que primero se hace es elegir la columna que quiero, ojalá una columna numerica
df_estudiantes["reading score"]

#sumar datos de una columna
df_estudiantes["reading score"].sum()

#como contar datos de una columna
df_estudiantes["reading score"].count()

#para obtener el promedio de una columna se utiliza el metodo mean
df_estudiantes["reading score"].mean()

#para calcular la desviación estandar de una columna uso el metodo std
df_estudiantes["reading score"].std()

#para ver los valores maximos de una columna uso el metodo max
df_estudiantes["reading score"].max()

#para ver el valor minimo de una columna uso el metodo min
df_estudiantes["reading score"].min()

#para ver las medidas de tendencia central de una columna
df_estudiantes["reading score"].describe()

#operaciones entre filas
df_estudiantes

#suma
df_estudiantes['math score']+df_estudiantes['writing score']+df_estudiantes['reading score']

#Asi guardo una nueva columna calculada
df_estudiantes['Total']=df_estudiantes['math score']+df_estudiantes['writing score']+df_estudiantes['reading score']
df_estudiantes

#ahora se calcula el promedio de los datos de las personas
(df_estudiantes['Total'])/3

df_estudiantes['Promedio']=(df_estudiantes['Total'])/3
df_estudiantes

#Asi se formatea los numeros para que no tengan más de 2 decimales
df_estudiantes.round(2)

#contar elementos por valor y se hace con len
len(df_estudiantes['gender'])

#para contar cada uno uso el metodo value.counts
df_estudiantes['gender'].value_counts()

#para contar la raza y grupos etnicos
df_estudiantes['race/ethnicity'].value_counts()

#asi puedo calcular el valor de participación por cada elemento
df_estudiantes['race/ethnicity'].value_counts(normalize=True)*100

#agrupar por la columna parental level of education
df_estudiantes['parental level of education'].value_counts()

#tambien puedo calcular el porcentaje de la participación por item
df_estudiantes['parental level of education'].value_counts(normalize=True)*100

df_estudiantes['gender'].value_counts(normalize=True)*100

#los valores más repetidos
df_estudiantes['math score'].value_counts()

#ordenamos los datos de manera ascendente
df_estudiantes.sort_values('math score')

#para guardarlo
df_estudiantes=df_estudiantes.sort_values('math score')
df_estudiantes

#para descargar la visual que acabo de crear
df_estudiantes.to_csv('df_estudiantes.csv', index=False)
df_estudiantes

df_estudiantes.sort_values("race/ethnicity", ascending=True,
                           key=lambda col:col.str.lower())