# -*- coding: utf-8 -*-
"""Cuaderno 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npz1EYEUntNvWeTgb38-NQtW5kYscSHp
"""

import pandas as pd
import numpy as np

df_estudiantes=pd.read_csv('/content/drive/MyDrive/p_hyton/StudentsPerformance (1).csv')
df_estudiantes

##creacion de columnas con el metodo assing o el insert
## para agregar varias colubnas uso assing y si quiero sobre escribir.

filosofia_scord=np.random.randint(1,100,size=1000)
fisica_scord=np.random.randint(1,100,size=1000)

filosofia_nota=pd.Series(filosofia_scord, index=np.arange(0,1000) )
fisica_nota=pd.Series(fisica_scord, index=np.arange(0,1000))

## poner las columnas nuevas al dataframe
df_estudiantes.assign(filosofia_score=filosofia_nota, fisica_score=fisica_nota)

df_estudiantes=df_estudiantes.assign(filosofia_score=filosofia_nota, fisica_score=fisica_nota)
df_estudiantes

## el metodo insert es diferente porque persmite especificar dosnde voy s colocar la colubna.
## para usar el metodo insert este no regresa cpias , hace cambio sobre la matriz.

df_estudiantes

## calcular el porcentage de participacion por item
df_estudiantes['parental level of education'].values_counts(normalize=True)*100