# -*- coding: utf-8 -*-
"""python_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/david22boxpersonal/ad13fa6518cfe58125e39db68de7a3ef/python_1.ipynb

**Buenos días** estoy aprendiendo Python, hace frio
"""

#Esto es muy divertido
print("Hola Mundo")

#Esta soy yo
print("Mi nombre es David, tengo 38 años trabajo en Galias y vivo en lujan")

"probando sin el print"

"""**TIPOS DE DATOS**"""

#TIPO DE DATO ENTERO, EN INGLES ES INTEGER Y LA ABREVIATURA ES INT
type(24)

#TIPO DE DATO FLOTANTE O DECIMAL SU ABREVUATURA ES FLOAT
type(3.0)

#BOLEANO VERDADERO O FALSO ABREVIATURA BOOL
type(True)

#tIPOLS DE DATOS CADENA SGTRING SIEMPRE CON COMILLAS SU ABREVIATURA STR
type("Alexandra Escobar")

"""METODOS DE LAS CADENAS, TIENEN FUNCIONES QUE ME AYUDAN A FORMATEARLAS"""

print("Hola estamos en clase de python".upper()) #este metodo me sirve para agregar mayusculas
print("Con Python puedo pEdir aumenTo".lower()) #este metodo me sirve para poner minusculas
print("Orgullo y prejuicio".title()) # este metodo me sirve para dejar el dato como titulo

#usaremos el metodo count --> Cuenta las letras de una cadena de texto
print("El párrafo generalmente lo definimos como un conjunto de oraciones escritas que comparten un tema y un contexto comunicativo, por lo que las escribimos en un orden, es decir, en secuencia. El párrafo también es considerado una de las unidades en que se puede dividir un texto escrito".count("a"))

print("""mi edad es 28 años,
mi genero es femenino""") # las 3 comillas sirven para hacer los saltos de linea

#reemplazar un valor de una cadena de texto utiliando replace
print("Esta cadena se reemplaza".replace("e","x"))

#reemplazar un valor de una cadena de texto utiliando replace
print("Esta cadena se reemplaza".replace("m","3"))

"""**VARIABLES**
Son espacios en memoria que nos ayudan a guardar informacipon en particular deben tener un nombre que nos ayudena a identificar su contenido
"""

#para declarar una variable se usa nombre de la variable, signo =, el valor:
#edad = 13
nombre="Alexandra"
apellido="Escobar Lozano"
edad=28
estado_civil="Casada"

print(nombre, apellido, edad, estado_civil)

#Nombre de hijo que no tengo
hijo_nombre="Miguel"
hijo_apellido="Monroy"
hijo_nombre

hijo_apellido

#Esta es una variable con un mensaje
mensaje_1="Ahora que sé python Alexandra no me va a ganar"

mensaje_1

#Acá no solo guarde la variable sino que muestro el valor de una vez
mensaje_2="Porque yo voy con toda"
mensaje_2

#Asi se concatena
mensaje_1 +" "+ mensaje_2

#Asi se declara una variable con un espacio en blanco
espacio=" "

mensaje_1 + espacio + mensaje_2

#Asi se guarda la concatenación dentro de una variable
mensaje_completo=mensaje_1+espacio+mensaje_2
print(mensaje_completo)

"""**LISTAS**

Son tipos de datos mutables y ordenados son las mas usadas al trabajar con datos, para declarar una lista uso los []
"""

#Las listas: se definen como el siguiente ejemplo:
#datos=["Maria", "Alexandra", "Escobar", "Lozano", 28, "Casada", 1.63]
Paises=["Colombia", "Perú", "Brasil", "Mexico", "China", "Francia", "Paraguay"]
Paises



#Las listas tienen indices automaticos que se generan cuando creo la lista sin embargo no son visibles hasta que las llamo
Paises[1]

#Llamar desde la derecha
Paises[-2]

#Llamar desde la izquierda
Paises[5]

#la tecnica del slicing me permite cortar pedazos de lista de una variable
Paises[1:3]

#Se almacena la cadena cortada en una nueva variable
corte_paises=Paises[1:3]
print(corte_paises)

Paises

Paises[1:]

Paises[:4]

#asi agrego un nuevo registro a la lista
Paises.append("Rusia")
Paises

# para agregar un dato en la posipción de la lista que yo quiera uso insert
Paises.insert(0,"Venezuela")
Paises

#tambien puedo concatenar listas
paises_europa=["italia", "alemania", "españa", "portugal", "polonia"]
paises_europa

Paises + paises_europa

paises_completo=Paises+paises_europa

paises_completo

paises_completos_lista=[Paises, paises_europa]
paises_completos_lista

########################Clase 1 de Octubre de 2024 ####################
##Crear una lista con los nombres, apellido edad cedula estado civil, estatura.
Nombre="David"
Apellido="Monroy"
Edad=38
Cedula=1010160983
Estado_civil="casado"
Estatura=170
Datos_personales=[Nombre,Apellido,Edad,Cedula,Estado_civil,Estatura]
print(Datos_personales)

## crear una lista con los familiares usando Append
Familiares=[]
Familiares.append("Luz Marina")
Familiares.append("Jairo Monroy")
Familiares.append("Liliana Monroy")
Familiares.append("Martin Monroy")
print(Familiares)

Familiares.insert(1,75)
Familiares

Familiares.insert(3,42)
Familiares

Familiares.insert(5,7)
Familiares

## esta funcion toma datos del usuario.###
edad_1=input("hola ingresa tu edad: ")

Hola VErifiquemos si eres mayor de edad

nombre

Paises

##Para remover datos de la lista uso REMOVE
Paises.remove("Rusia")
Paises

# para eliminar por posicion
Paises.pop(4)

## para eliminar definitivo
del Paises[5]
Paises

Paises

###ordena la lista de menr a mayor o alfanumerico metodo SORT
Paises.sort()
Paises

digitos=[2,4,1,6,0,3,8,7]
digitos.sort()
digitos

Paises.sort(reverse=True)
Paises

Paises_copia=Paises

"""Diccionario: Son tipos dedatos con llave y un valor a la combinaicon se le llama Items, en los diccionarios puedo usar metodos"""

diccionario_ing_esp={"casa":"hause","entender":"understand","sediento":"trirty","rojo":"red"}
diccionario_ing_esp

## para ver un valor de una llave determinada:
diccionario_ing_esp['casa']

## para traer todas las lleves:
diccionario_ing_esp.keys()

##para ver todo el diccionario
diccionario_ing_esp.items()

## para agregar un nuevo Diccionario
diccionario_ing_esp["rojo"]="red"
diccionario_ing_esp

## para actualizar los datos del diccionrio uso UPDATE
diccionario_ing_esp.update({"Negro":"Blanco"})
diccionario_ing_esp

## agregar otraa lista al diccionario:
diccionario_ing_esp.update({"gris":"grey","pronombre":["he","she","it"]})
diccionario_ing_esp



diccionario_ing_esp.values()

# Para borrar datos: metodo POP
diccionario_ing_esp.pop("gris")
diccionario_ing_esp

## para eliminar tambien se usa: del
del diccionario_ing_esp ["pronombre"]
diccionario_ing_esp

"""Operadores Logicos: se usan para comprobar condiciones, devolver TRUE o False, dependiendo del caso, claves para la toma de decisiones."""

## El primero es AND traduce Y.
print("operador and (que significa y)")
print("para que y sea verdadero todas las condiciones deben ser verdaderas")
5>3 and 5<10

5<3 and 5<10

##usamos OR es igul a O tener en cuenta la palabra or, una de las condiciones tiene que ser verdadera
5<3 or 5<10
5<3 or 5>10

## negacion NOT
print("operador NOT(negacion logica)")
not 5>3

"""Operador Matematico: Usaremos Suma, Resta, Multi, Divi, potenciacion, y modulo"""

## para la suma: + y me funciona para concatenar
6+5

## para la resta se representa con el -
6-5

## para la multiplicacion, *
4*5

## para dividir: /
6/5

## para potenciacion: ** Pimero la Base y despues el Exponente:
4**2

## para usar el Modulo: usamos el signo %
23%4

## operadores de comparacion: para comparar Valores, sabiendo que esta puede ser Verdadero o Falso.
## para comparar si los valores son = uso ==
(3+29)==21

##para comparar diferente de:
(3+29)!=21

## mayor que >
(3+29)>21

## menor Que <
(3+29)<21

## mayor y menor igual a: >=   <=
(3+29)>=21

(3+29)<=21

"""Condicionales: permiten ejecutar un codigo si la condicion es Verdadera o Falso, aplica comom entes de control, se escribe: **if**, **elif**, **else**"""

# if condicion
#( codigo que quiero ejecutar)
#else:
#(codigo a ejecutar)
edad_michael=16
if edad_michael >= 18:
  print("bienvenido, pero deberias estar trabajando")
else:
    print("Estas muy peque, no apostar")

edad_usuario=int(input("hola para ingresar comprueba tu edad"))
if edad_usuario >=18:
  print("Bienvenido puedes apostar")
else:
  print("Eres peque, no puedes apostar")

edad_usuario=int(input("hola para ingresar comprueba tu edad"))
if edad_usuario >=18:
  print("Bienvenido puedes apostar")
elif edad>=13:
  print("Eres pequeño prero te Esperamos")
else:
  print("Eres peque, no puedes apostar")

Paises

if "Francia" in Paises:
  print("esta no es una lista latinoamericana")
else:
  print("los sudacas")

if "Francia" not in Paises:
  print("esta no es una lista latinoamericana")
else:
  print("los sudacas")

"""Crea un programa que indique si una persona es mayor o menor de edad.

"""



edad = int(input("Ingresa tu edad: "))
if edad >= 18:
  print("Eres mayor de edad.")
else:
  print("Eres menor de edad.")

"""Crea una calculadora. que sume reste multiplique y divida. dos numeros proporcionados en Python"""

from __future__ import division
numero1 = int(input("Ingresa un numero: "))
numero2 = int(input("Ingresa un numero: "))
suma=numero1+numero2
resta=numero1-numero2
multiplicacion=numero1*numero2
division=numero1/numero2
print("resultado de la suma", suma)
print("resultado de la resta", resta)
print("resultado de la multiplicacion", multiplicacion)
print("resultado de la division", division)

"""Crea un programa que permita calcular"""

numero1 = int(input("Ingresa un numero a potencial: "))
multiplicacion2=numero1**2
print("resultado del cuadrado", multiplicacion2)

"""usa una condicional crea un programa que verifique si una persona tiene entre 13 y 18 años, o si es mayor de edad, pero tambien que me diga si es hombre o mujer."""

##genero1 = int(input("Ingresa tu genero: "))
##genero2 = int(input("Ingresa tu genero: "))
##genero3 = int(input("Ingresa tu genero: "))

edad = int(input("Ingresa tu edad: ", Genero))
if edad >= 18:
  print("Eres mayor de edad.", genero)
elif edad>=13:
  print("casi no pero ya casi.", genero)
elif edad>=0:
  print("Sos niño.", genero)

"""Escribe un diccionrio con"""

diccionario_ing_esp={"genero":"masculino","nombre":"david","edad":"38","descripcion":"relato"}
print diccionario_ing_esp

"""Aumentar a mayusculas"""

nombrenuevo = input("ingrese el noombre")
nombrenuevo.title()

"""crea dado el string de tu nombre, cambia la primer letra por otra."""

from re import A
nombrehumano = input("ingresa el nombre")
nombrehumano.replace (A)
print (nombrenuevo)

"""crea un programa que cuente la letra E en un Parrafo."""

escribe unna cadena de texto en MAyuscolas

Texto = input("esta es la clase python")
Texto.upper()

"""verifica si es par o inpar"""

numero1 = int(input("numero a comprovar"))
if numero1%2==0:
  print ("el numero es par")
else:
  print ("es Inpar")

"""Crea un programa: concatenar y mostrar

"""



"""CICLOS / BUCLES: Son estructuras de codigo que nos permite iterar sobre una estructura o rango.

Exsien 2 tipos muy usados (FOR= para) (while = mientras que)
"""

##de es esta manera es la estructura de FOR la palagbra for
##for<variable>int<lita>:
##  <Ejecutable>

Paises

Paises=["Colombia", "Perú", "Brasil", "Mexico", "China", "Francia", "Paraguay"]
Paises
for i in Paises:
  print(i)

for i in Paises:
  if i =="Mexico":
    print("Este pais es infiltrado")

for numero, i in enumerate(Paises):
  print(numero)
  print(i)

"""Funciones:"""

## len me da la longitud de un arreglo
## len toda funcion tiene parentecis
len(Paises)

## la funcnion max me sirve para mostrar el numero mas grande
max ([1,2,3,4,5])

## min para sacar el minimo
min ([1,2,3,4,5,6,7,8])

##type me sitve para saver el tipo de dato de una variable.
type(Paises)

## round para
round(1.144,678)

## rage para segir una secencia de numeros, tiene 3 el inicio el final el paso
contando=range(0,200,5)
for i in contando:

## def palabra reservada para declarar
def suma(a,b):
  resultado=a+b
  return resultado

suma(2,4)

def pan(a,b):
  resultado=a*b
  return resultado

pan(5,500)

cantidad= int(input("ingresa la cantidad de pan a llevar"))
Valordelpan= int(input("valor del pan"))
pan(cantidad,Valordelpan)

def division(a,b):
  resultado=a/b
  return=resultado



"""escribe un programa que calcule el total de una compra de supermercado, el usuario debe ingresar el valor de los productos y as cantidad des que desea comprar de cada uno, después el programa deberá permitir: sumar los precios de los productos. multiplicar los precios por las cantidades de productos, restar un descuento del pecio total (si tiene cupón) ; dividir el total entre dos personal para dividir la cuenta.   ojo Multiplica, suma resta y divide."""

## declaro variables
##Productos= [arroz,frijoles,maiz,croquetas,carne,papas]
def suma(a+b):
  resulado_suma=a+b
  return resulado_suma
def multiplicacion(a*b):
  resultado_multi=a*b
  return resultado_multi
def division(a/b):
  if b !=0:
    return a/b
    else:
      return print("nose puede dividir entre 0")
def resta(a-b)
  resultado_resta=a-b
  return resultado_resta

print("bienvenido")
precio_1 float(input("ingresa el valor del producto 1"))
precio_2 float(input("ingresa el valor del producto 2"))



"""# Nueva sección"""